modules/site_commerce_product/src/Form/ProductAttributeDeleteForm.php
<?php

namespace Drupal\site_commerce_product\Form;

use Drupal\Core\Entity\ContentEntityDeleteForm;
use Drupal\Core\Url;

/**
 * Provides a deletion confirmation form for attribute entity.
 *
 * @internal
 */
class ProductAttributeDeleteForm extends ContentEntityDeleteForm {

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    // The cancel URL is the group collection.
    return new Url('entity.site_commerce_attribute_group.collection');
  }

  /**
   * {@inheritdoc}
   */
  protected function getRedirectUrl() {
    return $this->getCancelUrl();
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('Deleting a attribute will delete all its children if there are any. This action cannot be undone.');
  }

  /**
   * {@inheritdoc}
   */
  protected function getDeletionMessage() {
    return $this->t('Deleted attribute %name.', ['%name' => $this->entity->label()]);
  }

}

modules/site_commerce_product/templates/site-commerce-product-add-list.html.twig
{% if types is not empty %}
    <dl>
        {% for type in types %}
            <dt>
                <a href="{{ type.url }}">{{ type.label }}</a>
            </dt>
        {% endfor %}
    </dl>
{% endif %}

modules/site_commerce_product/templates/site-commerce-product-catalog-children-list.html.twig
{% if categories %}
	<ul class="site-commerce-product-catalog-children-list">
		{% for tid, data in categories %}
			<li class="site-commerce-product-catalog-children-list__item">
				{% if data.count_products %}
					<a class="site-commerce-product-catalog-children-list__link" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': tid}) }}">{{ data.name }}</a> ({{ data.count_products }})
				{% else %}
						<a class="site-commerce-product-catalog-children-list__link" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': tid}) }}">{{ data.name }}</a>
				{% endif %}
			</li>
		{% endfor %}
	</ul>
{% endif %}

modules/site_commerce_product/templates/site-commerce-product-catalog-media-image.html.twig
{% for delta, image in data %}
  <div class="site-commerce-product-catalog-media-image">
    <img
    width="{{ image.style_width }}px"
    height="{{ image.style_height }}px"
    class="site-commerce-product-catalog-media-image__item"
    src="{{ image.style_url }}" loading="lazy"
    alt="{{ image.alt }}"
    />
  </div>
{% endfor %}

modules/site_commerce_product/templates/site-commerce-product-catalog-products-preview.html.twig
{{ attach_library('kvantstudio/utilities') }}

<div id="catalog-products-preview" class="catalog-products-preview">
  {% for key, data in products %}
    <div class="catalog-products__category">
      {% if data.name %}
        <div class="catalog-products__category-title">
          {% if data.tid %}
            <a class="catalog-products__category-title-link" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': data.tid}) }}">
              <span class="catalog-products__category-title-header">{{ data.name }}</span>
            </a>
          {% else %}
            <span class="catalog-products__category-title-header">{{ data.name }}</span>
          {% endif %}
        </div>
        {% if data.summary %}
          <div class="catalog-products__category-summary">{{- data.summary|raw -}}</div>
        {% endif %}
      {% endif %}

      <div class="catalog-products__items">
        {% for product_id, item in data.items %}

          {% set classes_item = 'catalog-products__item' %}
          {% if item.quantity_stock_allow and item.quantity_stock_value == 0 %}
            {% set classes_item = 'catalog-products__item catalog-products__item_not-in-stock' %}
          {% endif %}

          <div class="{{ classes_item }}">
            <a class="catalog-products__item-link" href="{{ path('entity.site_commerce_product.canonical', {'site_commerce_product':product_id}) }}">
              {# Изображение товара #}
              <div class="catalog-products__item-element catalog-products__item-image">
                {{ item.field_media_image }}
              </div>

              {% set stockStatus = site_commerce_product_status_stock(item.site_commerce_product) %}
              {% if stockStatus %}
                <div class="catalog-products__item-element catalog-products__item-stock-status">{{ stockStatus }}</div>
              {% endif %}

              {# Цена товара #}
              <div class="catalog-products__item-element catalog-products__item-cost">
                {{ item.price }}
              </div>

              {# Количество на складе #}
              {% if item.quantity_stock_allow %}
                <div class="catalog-products__item-element catalog-products__item-quantity">
                  {% if item.quantity_stock_value %}
                    {{ 'In stock'|t }}&nbsp;{{- item.quantity_stock_value -}}&nbsp;{{- item.quantity_unit -}}
                  {% else %}
                    {{ 'Out of stock'|t }}
                  {% endif %}
                </div>
              {% endif %}

              {# Название товара #}
              <div class="catalog-products__item-element catalog-products__item-title">
                {% set title = item.title | render | striptags %}
                {{ title|length > 155 ? title|slice(0, 155) ~ '...' : title }}
              </div>

              {% if item.site_commerce_product.field_summary_catalog.value %}
                <div class="catalog-products__item-element catalog-products__item-details">
                  {{ item.site_commerce_product.field_summary_catalog.value|striptags }}
                </div>
              {% endif %}

              <div class="catalog-products__item-add-to-cart-form">
                {{ item.add_cart_form }}
              </div>
            </a>
          </div>
        {% endfor %}
      </div>

      {% if data.tid %}
        <div class="catalog-products__read-more">
          <span class="catalog-products__read-more-category js-open-link" data-link="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': data.tid}) }}">
            {{ 'View all products'|t }}
            <svg class="b__pnPHbRM5M" xmlns="http://www.w3.org/2000/svg" width="6" height="10" viewbox="0 0 6 10" data-tid="ee3cea8f">
              <path d="M0.26539524,1.62627039 C-0.13724966,1.20513402 -0.0724902,0.554478684 0.39684933,0.208682552 C0.82663343,-0.107970248 1.45004248,-0.0601558306 1.81751265,0.324190408 L6.04898799,4.74999631 L1.81751265,9.17580221 C1.45004248,9.56014844 0.82663343,9.60796286 0.39684933,9.29131006 C-0.0724902,8.94551393 -0.13724966,8.29485859 0.26539524,7.87372222 L3.25196299,4.74999631 L0.26539524,1.62627039 Z"></path>
            </svg>
          </span>
        </div>
      {% endif %}
    </div>
  {% endfor %}
</div>

modules/site_commerce_product/templates/site-commerce-product-catalog-products.html.twig
{{ attach_library('kvantstudio/utilities') }}

<div id="catalog-products" class="catalog-products">
  {# Фильтры поиска по каталогу #}
  <div id="catalog-products-filters" class="catalog-products-filters">
    <div id="catalog-products-filters-categories" class="catalog-products-filters-categories">
      <span class="catalog-products-filters-categories__root">
        {{ 'Category'|t }}
      </span>
      {% if category.parents is not empty %}
        <div id="catalog-products-filters-categories__parents" class="catalog-products-filters-categories__parents">
          {% for tid, data in category.parents %}
            <div class="catalog-products-filters-categories__parents-item">
              <a class="catalog-products-filters__link catalog-products-filters__link-category catalog-products-filters__link-category_parent" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': tid}) }}">
                <svg viewbox="0 2 14 14" width="10" height="10" fill="none" xmlns="http://www.w3.org/2000/svg" class="catalog-products-filters__arrow-back">
                  <path d="M5.293 12.293a1 1 0 101.414 1.414l5-5a1 1 0 000-1.414l-5-5a1 1 0 00-1.414 1.414L9.586 8l-4.293 4.293z" fill="currentColor"></path>
                </svg>
                {{ data.name }}
              </a>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <a class="catalog-products-filters__link catalog-products-filters__link-category catalog-products-filters__link-category_parent" href="/{{ category.root }}">
          <svg viewbox="0 2 14 14" width="10" height="10" fill="none" xmlns="http://www.w3.org/2000/svg" class="catalog-products-filters__arrow-back">
            <path d="M5.293 12.293a1 1 0 101.414 1.414l5-5a1 1 0 000-1.414l-5-5a1 1 0 00-1.414 1.414L9.586 8l-4.293 4.293z" fill="currentColor"></path>
          </svg>
          {{ 'Go to catalog'|t }}
        </a>
      {% endif %}

      {% if category.name is not empty %}
        <div class="catalog-products-filters-categories__current">
          {{ category.name }}
        </div>
      {% endif %}

      {% if categories is not empty %}
        <div id="catalog-products-filters-categories__items" class="catalog-products-filters-categories__items">
          {% for tid, data in categories %}
            <div class="catalog-products-filters-categories__item">
              <a class="catalog-products-filters__link catalog-products-filters__link-category" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': tid}) }}">
                {% if data.count %}
                  {{ data.name }} <span class="catalog-products-filters__count">({{ data.count }})</span>
                {% else %}
                  {{ data.name }}
                {% endif %}

              </a>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </div>

  {# Перечень товаров #}
  <div id="catalog-products-data" class="catalog-products-data">
    {% for key, data in products %}
      <div class="catalog-products__category">
        {% if data.name %}
          <div class="catalog-products__category-title">
            {% if data.tid %}
              <a class="catalog-products__category-title-link" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term': data.tid}) }}">
                <span class="catalog-products__category-title-header">{{ data.name }}</span>
              </a>
            {% else %}
              <span class="catalog-products__category-title-header">{{ data.name }}</span>
            {% endif %}
          </div>
          {% if data.summary %}
            <div class="catalog-products__category-summary">{{- data.summary|raw -}}</div>
          {% endif %}
        {% endif %}

        <div id="catalog-products__items" class="catalog-products__items">
          {% for product_id, item in data.items %}

            {% set classes_item = 'catalog-products__item' %}
            {% if item.quantity_stock_allow and item.quantity_stock_value == 0 %}
              {% set classes_item = 'catalog-products__item catalog-products__item_not-in-stock' %}
            {% endif %}

            <div class="{{ classes_item }}">
              <a class="catalog-products__item-link" href="{{ path('entity.site_commerce_product.canonical', {'site_commerce_product':product_id}) }}">
                {# Изображение товара #}
                <div class="catalog-products__item-element catalog-products__item-image">
                  {{ item.field_media_image }}
                </div>

                {% set stockStatus = site_commerce_product_status_stock(item.site_commerce_product) %}
                {% if stockStatus %}
                  <div class="catalog-products__item-element catalog-products__item-stock-status">{{ stockStatus }}</div>
                {% endif %}

                {# Цена товара #}
                <div class="catalog-products__item-element catalog-products__item-cost">
                  {{ item.price }}
                </div>

                {# Количество на складе #}
                {% if item.quantity_stock_allow %}
                  <div class="catalog-products__item-element catalog-products__item-quantity">
                    {% if item.quantity_stock_value %}
                      {{ 'In stock'|t }}&nbsp;{{- item.quantity_stock_value -}}&nbsp;{{- item.quantity_unit -}}
                    {% else %}
                      {{ 'Out of stock'|t }}
                    {% endif %}
                  </div>
                {% endif %}

                {# Название товара #}
                <div class="catalog-products__item-element catalog-products__item-title">
                  {% set title = item.title | render | striptags %}
                  {{ title|length > 155 ? title|slice(0, 155) ~ '...' : title }}
                </div>

                {% if item.site_commerce_product.field_summary_catalog.value %}
                  <div class="catalog-products__item-element catalog-products__item-details">
                    {{ item.site_commerce_product.field_summary_catalog.value|striptags }}
                  </div>
                {% endif %}

                <div class="catalog-products__item-add-to-cart-form">
                  {{ item.add_cart_form }}
                </div>
              </a>
            </div>
          {% endfor %}
        </div>

      </div>
    {% endfor %}
  </div>
</div>

modules/site_commerce_product/templates/site-commerce-product-catalog.html.twig
<div class="site-commerce-product-catalog">
  {% for tid, data in categories %}
    <div class="site-commerce-product-catalog__item">
      {% if data.field_media_image %}
        <div class="site-commerce-product-catalog__image">{{ data.field_media_image }}</div>
      {% endif %}
      <div class="site-commerce-product-catalog__title">
        <a class="site-commerce-product-catalog__link" href="{{ path('entity.taxonomy_term.canonical', {'taxonomy_term':tid})}}">{{ data.name }}</a>
      </div>
      {# Подкатегории корневой категории товаров #}
      {{ site_commerce_product_catalog_children_list(tid, 1) }}
    </div>
  {% endfor %}
</div>

modules/site_commerce_product/templates/site-commerce-product-characteristics-editor.html.twig
<table class="site-commerce-characteristics">
    <tbody>
        {% for gid, data in groups %}
            <tr>
                <td class="site-commerce-characteristics__group-title">
                    {{ data.title }}
                </td>
                <td class="site-commerce-characteristics__item-title">
                    <i class="fas fa-edit"></i>
                    <a href="/admin/config/kvantstudio/site-commerce-characteristics-group/{{ gid }}" class="use-ajax" data-dialog-type="modal">{{ 'Edit'|t }}</a>
                    <i class="fas fa-trash-alt"></i>
                    <a href="/admin/config/kvantstudio/site-commerce-characteristics-group-confirm-delete/{{ gid }}" class="use-ajax" data-dialog-type="modal">{{ 'Delete'|t }}</a>
                </td>
            </tr>
            {% for cid, characteristic in data.characteristics %}
                <tr>
                    <td class="site-commerce-characteristics__item-title">
                        <div class="site-commerce-characteristics__item-title-dots">
                            <span class="site-commerce-characteristics__item-title-dots-span">
                                {{ characteristic.title }}
                                {% if characteristic.description is not empty %}
                                    <a href="#" data-tooltip-content="#site-commerce-characteristics__tooltip-{{ cid }}" class="tooltip-click site-commerce-characteristics__item-title-dots-icon">
                                        <i class="far fa-question-circle"></i>
                                    </a>
                                {% endif %}
                            </span>
                            <div class="site-commerce-characteristics__tooltip">
                                <span id="site-commerce-characteristics__tooltip-{{ cid }}">{{ characteristic.description }}</span>
                            </div>
                        </div>
                    </td>
                    <td class="site-commerce-characteristics__item-title">
                        <i class="fas fa-edit"></i>
                        <a href="/admin/config/kvantstudio/site-commerce-characteristics-item/{{ cid }}" class="use-ajax" data-dialog-type="modal">{{ 'Edit'|t }}</a>
                        <i class="fas fa-trash-alt"></i>
                        <a href="/admin/config/kvantstudio/site-commerce-characteristics-item-confirm-delete/{{ cid }}" class="use-ajax" data-dialog-type="modal">{{ 'Delete'|t }}</a>
                    </td>
                </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>

modules/site_commerce_product/templates/site-commerce-product-export-price.html.twig
{{ form }}

modules/site_commerce_product/templates/site-commerce-product-field-cost-multiple-value-form.html.twig
{# Шаблон оформления мультиформы создания стоимости товара с учетом ценовых групп. #}
{{ form }}

modules/site_commerce_product/templates/site-commerce-product-form.html.twig
{#
/**
 * @file
 * Two column template for the product add/edit form.
 */
#}
<div class="layout-product-form clearfix">
    <div class="layout-region layout-region-product-main">
        {{ form|without('advanced', 'actions') }}
    </div>
    <div class="layout-region layout-region-product-secondary">
        {{ form.advanced }}
    </div>
    <div class="layout-region layout-region-product-footer">
        {{ form.actions }}
    </div>
</div>

modules/site_commerce_product/templates/site-commerce-product-get-price.html.twig
{{ form }}

modules/site_commerce_product/templates/site-commerce-product-settings.html.twig
<div class="site-commerce-settings">

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'New product'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.status_new }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Appearance'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.status_appearance }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Stock availability'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.status_stock }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Allow displaying the quantity in stock'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.quantity_stock_allow }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Quantity in stock'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.quantity_stock_value }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Unit of quantity measurement'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.quantity_unit }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Type of sale'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.status_type_sale }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Minimum order quantity'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.quantity_order_min }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Maximum order quantity'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.quantity_order_max }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Allow displaying the add to cart form'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.cart_form_allow }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Allow changing the quantity of products in the cart'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.cart_quantity_allow }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Event after adding to cart'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.cart_after_adding_event }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Button name adding to cart'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.cart_label_button_add }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		<div class="site-commerce-settings__title">
			{{ 'Button name buy in one click'|t }}
		</div>
		<div class="site-commerce-settings__data">
			{{ form.cart_label_button_click }}
		</div>
	</div>

	<div class="site-commerce-settings__block">
		{{ form.cart_description }}
	</div>
</div>

modules/site_commerce_product/templates/site-commerce-product-views-products-catalog.html.twig
{{ products }}

modules/site_commerce_product/templates/site-commerce-product.html.twig
{# Подключаем библиотеку оформления #}
{{ attach_library('site_commerce_product/product') }}

{# Кнопки администрирования карточкой товара. #}
{# {% if logged_in and user.hasPermission('administer site_commerce') %}
  {{ attach_library('core/drupal.dialog.ajax') }}
  <h3>Функции администрирования в разработке (не использовать на рабочем проекте)</h3>
  <div class="site-commerce-administer-block">
    <button class="btn btn-primary use-ajax" data-dialog-type="modal" href="{{ path('site_commerce.products.create_version', {'pid': content.pid, 'clone_pid': content.pid}) }}" data-dialog-options='{"width":800}'>
      {{ "Create copy of product"|t }}
    </button>

    <button class="btn btn-primary use-ajax" data-dialog-type="modal" href="{{ path('site_commerce.product_characteristic_add_form', {'pid': content.pid}) }}" data-dialog-options='{"width":800}'>
      {{ "Add characteristic"|t }}
    </button>
  </div>
{% endif %} #}

<article{{attributes}}>
  <div class="product">

    {# Содержимое над карточкой товара #}
    {# {% if not (content.field_content_above.isEmpty == true) and content.field_content_above is defined %} #}
    {% if content.field_content_above[0] is not empty %}
      <div class="product__content-above">
        {{- content.field_content_above -}}
      </div>
    {% endif %}

    <div class="product__view">
      {# Изображения товара #}
      <div class="product__images">
        {# Изображения товаров #}
        {{ content.field_media_image }}
      </div>

      <div class="product__cart">
        {# Заголовок страницы #}
        {% if title %}
          <h1 class="page-title product__title">{{- title -}}</h1>
        {% endif %}

        {# Основные параметры товара #}
        {% if basic_parametrs %}
          <div class="product__basic-parametrs">
            {# Код товара на складе #}
            {% if code %}
              <div class="product__basic-parametrs-item">
                {{ 'Product code'|t }}:&nbsp;{{- code -}}
              </div>
            {% endif %}

            {# Номер по каталогу производителя #}
            {% if code_manufacturer %}
              <div class="product__basic-parametrs-item">
                {{ 'Catalog number'|t }}:&nbsp;{{- code_manufacturer -}}
              </div>
            {% endif %}

						{# Количество товара на складе #}
						{% if quantity_stock_allow and quantity_stock_value %}
							<div class="product__basic-parametrs-item">
								{{ 'In stock'|t }}&nbsp;{{- quantity_stock_value -}}&nbsp;{{- quantity_unit -}}
							</div>
						{% endif %}
          </div>
        {% endif %}

        {# Стоимость товара #}
        {{ content.price }}

        {# Если разрешено добавлять товар в корзину #}
        {% if cart %}
          {# Краткое описание над корзиной в карточке товара #}
          {% if cart_description %}
            <div class="product__cart-description">{{- cart_description -}}</div>
          {% endif %}

          {# Форма добавления в корзину #}
          <div class="product__cart-data">
            {{ cart.data }}
          </div>
        {% endif %}

        {# Краткое описание товара #}
        {% if content.field_summary[0] is not empty %}
          <div class="product__summary">{{- content.field_summary -}}</div>
        {% endif %}
      </div>
    </div>

    {# Основное содержимое карточки товара #}
    {% if content.field_content[0] is not empty %}
      <div class="product__content">
        {{- content.field_content -}}
      </div>
    {% endif %}
  </div>
</article>